version: "3.8"

services:
  app:
    image: namanrai1403/nodejs-app:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./logs:/usr/src/app/logs
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (r) => r.statusCode === 200 ? process.exit(0) : process.exit(1))",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
