version: "3.8"

services:
  app:
    image: namanrai1403/nodejs-app:latest # Updated correct image name
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
