name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to docker hub
        uses: docker/login-action@v2 # More secure than using -u -p
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:${{ github.sha }} -t ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:latest .

      - name: Publish image to docker hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:${{ github.sha }}

      - name: Delete old container
        run: docker rm -f nodejs-app-container || true # Won't fail if container doesn't exist

      - name: Run docker container
        run: |
          docker run -d \
            -p 3000:3000 \
            -e NODE_ENV=production \
            -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            -e AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }} \
            -v ./logs:/usr/src/app/logs \
            --health-cmd="curl -f http://localhost:3000/health" \
            --health-interval=30s \
            --health-timeout=10s \
            --health-retries=3 \
            --name nodejs-app-container \
            --restart unless-stopped \
            ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:${{ github.sha }}

      - name: Clean up old images
        run: docker system prune -f
