name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2 # More secure than using -u -p
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:${{ github.sha }} \
                       -t ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:latest .

      - name: Publish image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:${{ github.sha }}

      - name: Delete old container
        run: docker rm -f nodejs-app-container || true # Won't fail if container doesn't exist

      - name: Run Docker container
        run: |
          docker run -d \
            -p 3000:3000 \
            --name nodejs-app-container \
            --restart unless-stopped \
            --env NODE_ENV=production \
            --env MONGODB_URI=${{ secrets.MONGODB_URI }} \
            --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            --env AWS_REGION=${{ secrets.AWS_REGION }} \
            --env AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }} \
            ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-app:${{ github.sha }}

      - name: Clean up old images
        run: docker system prune -f
